name: Trigger auto deployment for container-app-5l5v4x2xmi2ny

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-5l5v4x2xmi2ny-AutoDeployTrigger-19ea9f5f-c57e-4bfa-8f2a-f4d8872528c8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP5L5V4X2XMI2NY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP5L5V4X2XMI2NY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP5L5V4X2XMI2NY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP5L5V4X2XMI2NY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP5L5V4X2XMI2NY_REGISTRY_PASSWORD }}
          containerAppName: container-app-5l5v4x2xmi2ny
          resourceGroup: flaskbasicb9018cff
          imageToBuild: default/container-app-5l5v4x2xmi2ny:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


